---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd
  labels:
    app: l5d
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: linkerd
  labels:
    app: l5d
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-allow-all
subjects:
- kind: ServiceAccount
  name: linkerd
  namespace: linkerd
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-allow-all
  labels:
    app: l5d
rules:
  - apiGroups: [""]
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
data:
  config.yaml: |-
    admin:
      port: 9990

    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25

    routers:
    - protocol: h2
      label: outgoing
      experimental: true
      dtab: |
        /srv        => /#/io.l5d.k8s/linkerd/grpc;
        /grpc       => /srv;
        /grpc/Echo => /srv/vertx-grpc-echo-server;
        /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
      identifier:
        kind: io.l5d.header.path
        segments: 1
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: linkerd
          port: incoming
          service: l5d
          hostNetwork: true
      servers:
      - port: 4140
        ip: 0.0.0.0

    - protocol: h2
      label: incoming
      experimental: true
      dtab: |
        /srv        => /#/io.l5d.k8s/linkerd/grpc;
        /grpc       => /srv;
        /grpc/Echo => /srv/vertx-grpc-echo-server;
        /svc        => /$/io.buoyant.http.domainToPathPfx/grpc;
      identifier:
        kind: io.l5d.header.path
        segments: 1
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
          hostNetwork: true
      servers:
      - port: 4141
        ip: 0.0.0.0
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      serviceAccount: linkerd
      hostNetwork: true
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        image: buoyantio/linkerd:1.0.2
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - /io.buoyant/linkerd/config/config.yaml
        ports:
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: incoming
          containerPort: 4141
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true

      - name: kubectl
        image: buoyantio/kubectl:v1.4.0
        args:
        - "proxy"
        - "-p"
        - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: l5d
  #annotations:
  #  service.beta.kubernetes.io/aws-load-balancer-internal: '0.0.0.0/0'
spec:
  selector:
    app: l5d
  type: ClusterIP
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990
